blank_issues_enabled: true
contact_links:
  - name: I want help with this repository
    url: https://github.com/brunotacca/poc_cleanarch_spring_multimodules/discussions
    about: Ask your questions about how to achieve a particular objective within this project.