name: Generate Extra Docs

on:
  push:
    branches:
      - main
    paths:
      - 'ca-spring-multimodule/external/apis/docs/docbook/**'
  
jobs:
  generate-md:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: docker://pandoc/core:2.19
        with:
          args: -f docbook -t markdown_strict ca-spring-multimodule/external/apis/docs/docbook/api-guide.xml -o ca-spring-multimodule/external/apis/docs/md/api-guide.md
      
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Adding Generated Markdown Docs
